version: "3.8"
services:
  dbserver-svc:
    build:
      context: ./docker-file/db
    image: opeseen/dbimagebk
    container_name: dbserver
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin@root
    volumes:
      - dbData:/var/lib/mysql

  appserver-svc:
    build:
      context: ./docker-file/app
    image: opeseen/appimagebk
    container_name: appserver
    ports: 
      - "8080:8080"
    depends_on:
      - dbserver-svc
    command: bash -c "./wait-for-it.sh --timeout=60 --strict dbserver:3306 && java -jar banking-v1.jar"
    restart: on-failure

  webserver-svc:
    build:
      context: ./docker-file/web
    image: opeseen/webimagebk
    container_name: webserver
    depends_on:
      - appserver-svc
    ports:
      - "80:80"
    restart: on-failure

volumes:
  dbData: {}