version: "3.8"
services:
  appdbsvc:
    build:
      context: ./docker-file/db
    image: opeseen/bankappdb
    container_name: appdb
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin@root
    volumes:
      - dbData:/var/lib/mysql

  appsvc:
    build:
      context: ./docker-file/app
    image: opeseen/bankapp
    container_name: app
    ports: 
      - "8080:8080"
    depends_on:
      - appdbsvc
    command: bash -c "./wait-for-it.sh --timeout=60 --strict appdb:3306 && java -jar banking-v1.jar"
    restart: on-failure

volumes:
  dbData: {}