version: "3.8"
services:
  appdb:
    build:
      context: ./docker-file/db
    container_name: appdb
    ports: 
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=admin@root
    volumes:
      - dbData:/var/lib/mysql

  app:
    build:
      context: ./docker-file/app
    container_name: app
    ports: 
      - "8080:8080"
    depends_on:
      - appdb
    restart: on-failure

volumes:
  dbData: {}